services:
  portfolio:
    image: ${DOCKER_HUB_USERNAME}/portfolio-react:latest
    container_name: portfolio-site
    restart: always
    expose:
      - "80"

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt